@extends('layout')

@section('title', 'MSU FACULTY DIRECTORY')

@section('content')
<div class="container border mt-3">
    <h1>College of Engineering</h1>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas tenetur, vitae error quo itaque aliquid asperiores quod magnam corporis inventore in quis! Officiis laudantium magni qui reprehenderit autem suscipit. Facere porro repellendus in. Porro ipsam magni quisquam! Qui sed, unde adipisci impedit perferendis culpa doloribus rerum quia ipsa distinctio eum id quos corrupti consequuntur, explicabo eveniet excepturi quod repudiandae labore maxime hic enim, suscipit optio itaque! Inventore, aliquam quisquam rem quasi aspernatur vitae ipsam quae reiciendis velit et hic porro explicabo architecto consectetur illo aliquid, quidem modi amet numquam necessitatibus nisi. Labore autem incidunt porro obcaecati. Repellendus deserunt ratione maxime amet, obcaecati debitis accusamus temporibus a officia ut? Fugit mollitia earum eum quos facilis, laboriosam, veniam aliquid voluptate ducimus animi ipsa, quidem numquam libero odio repudiandae hic cumque! Quia adipisci excepturi fugit earum nisi perspiciatis commodi? Consectetur tenetur quasi rerum, doloremque voluptatem reprehenderit voluptates commodi. Fugiat quam, quaerat voluptatem, ullam voluptates voluptatum, molestias facilis rerum nisi modi autem incidunt quod placeat inventore aut. Sed, odit delectus? Blanditiis a modi commodi natus cum consequatur laborum saepe facilis fugiat laudantium repellat officia voluptatibus repudiandae necessitatibus asperiores nemo dolor, ipsam sequi labore. Vel quam hic harum aut velit necessitatibus doloribus deleniti consectetur aliquid. Eum temporibus minima, placeat id at, enim non quia ratione rerum quo voluptate atque quidem dignissimos provident deleniti incidunt numquam. Architecto exercitationem deleniti nemo totam fugit quo voluptatem, molestiae laboriosam consequatur, eos labore quod iste? Assumenda maxime soluta error ratione! Fugiat a voluptatibus consequuntur commodi atque explicabo itaque, dolorum numquam culpa. Dolor reprehenderit aspernatur quia dolorum dolorem iusto ipsam cupiditate reiciendis nostrum architecto. Magni ratione debitis ipsa eligendi repudiandae aliquam! Aspernatur, laboriosam tempora iusto quaerat at pariatur neque, voluptas ipsum nemo, velit quidem saepe eligendi tempore quos et nesciunt animi esse cumque minima quod aut corporis corrupti accusantium laborum. Perferendis.
</div>
@endsection
