@extends('layout')

@section('title', 'MSU FACULTY DIRECTORY')

@section('content')
<div class="container border mt-3">
    <h1>Hello World</h1>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis aut eveniet amet omnis, enim sint asperiores doloremque nesciunt, autem deserunt repudiandae blanditiis. Nihil, quis reprehenderit laboriosam provident beatae explicabo deserunt ducimus, inventore iure hic deleniti officia alias dolores veritatis libero tenetur, quisquam cupiditate laborum velit odio repudiandae cum doloremque. Repudiandae, optio deserunt? Quia fuga eligendi aliquam enim nisi, eos, quod libero quae praesentium similique, nobis perferendis rem incidunt magni ex ullam consequuntur a. Aut exercitationem animi aspernatur, nostrum veritatis quas illo nulla esse, necessitatibus eligendi nihil maxime, dolore pariatur quasi assumenda id quam perferendis ea quidem rem temporibus asperiores omnis rerum! Tempore reprehenderit quaerat quas? Fugit libero iusto voluptatem eius beatae illum placeat cupiditate sed aperiam dolorum necessitatibus odit, temporibus totam accusamus suscipit, quis excepturi qui corrupti. Voluptatum praesentium porro iste nostrum labore quidem quas, necessitatibus commodi eius unde dolor maiores ipsam aliquid voluptate quae veritatis, cum nihil facilis reiciendis saepe, repudiandae ab soluta nesciunt non. Iusto, provident odit. Suscipit maxime eveniet obcaecati optio ratione. Consequuntur totam architecto eaque nisi quo maiores corrupti a deleniti illo vero? Asperiores in dignissimos, amet recusandae rem harum at distinctio. Rerum, nemo sunt? Facilis, facere laborum expedita adipisci nostrum quisquam quasi doloremque iusto blanditiis quos. Deserunt, totam quisquam! Reprehenderit molestias rerum hic quis, recusandae impedit necessitatibus, nam eligendi dolor facere suscipit aspernatur quisquam unde neque totam accusantium quaerat minima sapiente in qui eos nisi distinctio. Ipsam sint ex rem maxime architecto ad! Doloremque, velit sunt eos blanditiis minus quasi a facere ducimus, optio et iste saepe modi odit mollitia non amet molestias molestiae? Provident esse praesentium ea nesciunt obcaecati. Nemo rem fugit necessitatibus laborum hic, impedit atque provident aperiam facilis minima doloribus totam vel sit tempora tenetur culpa fuga porro quasi aliquid earum, saepe modi animi! Et similique eligendi iusto blanditiis consequatur distinctio corporis.
</div>
@endsection
